---

- name: load jupyterhub supervisor config
  supervisorctl: name=jupyterhub state=present

- name: restart jupyterhub with supervisor
  supervisorctl: name=jupyterhub state=restarted
  ignore_errors: yes

# Must ignore errors because JupyterHub sucks.
# See https://github.com/jupyterhub/jupyterhub-deploy-teaching/issues/104.
