---

# Creates the nbgrader directory and sets up users' configuration accordingly.
# Only users that belong in the teachers group get access to the directory.

- name: create the submissions directory
  file:
    path: "{{ submissions_prefix }}"
    state: directory
    owner: root
    group: teachers
    mode: 02775
    recurse: yes

- name: extract all teachers
  set_fact:
    teachers: "{{ jupyterhub_groups | selectattr('name', 'equalto', 'teachers')
                                    | map(attribute='members') | first }}"
- name: extract all students
  set_fact:
    teachers: "{{ jupyterhub_groups | selectattr('name', 'equalto', 'students')
                                    | map(attribute='members') | first }}"

- name: install the nbgrader configuration files
  template:
    src: nbgrader_config.py.j2
    dest: "/home/{{ item }}/.jupyter/nbgrader_config.py"
  become: true
  become_user: item
  loop: "{{ teachers }}"

- name: add students to database
  command: nbgrader db student add {{ item }}
  become: true
  become_user: "{{ teachers | first }}"
  loop: "{{ students }}"
