---

# Creates the nbgrader directory and sets up users' configuration accordingly.
# Adds students to the database.

- name: create the submissions directory
  file:
    path: "{{ submissions_prefix }}"
    state: directory
    owner: root
    group: teachers
    mode: 02775
    recurse: yes

- name: copy the grade exporter script file to the submissions directory
  copy: src=md_exporter.py dest={{ submissions_prefix }} owner=root group=teachers mode=0750

- name: set up teachers
  include_tasks: teachers.yml
  loop: "{{ teachers }}"
  loop_control:
    loop_var: teacher

- name: read student information from file
  include_tasks: students.yml
  when: students_tsv is defined and students_tsv

- name: add students to database
  command: "nbgrader db student add {{ item }} {{ (students_dict|default({})).get(item, '') }}"
  args:
    chdir: "/home/{{ teachers | first }}"
  become: true
  become_user: "{{ teachers | first }}"
  loop: "{{ students }}"
